name: isolate_logger
description: A logger utility for logging messages into console & in files, which will help users to track for any user events/exceptions etc.
version: 1.0.7
homepage: https://github.com/aliasgar4558/isolate_logger
repository: https://github.com/aliasgar4558/isolate_logger
issue_tracker: https://github.com/aliasgar4558/isolate_logger/issues

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  archive: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
