name: isolate_logger
description: A logger utility for logging messages into console & in files, which will help users to track for any user events/exceptions etc.
version: 1.0.6

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.3
  intl: ^0.19.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
